baseURL: "https://smc.im/"
title: Choi's Notes
languageCode: zh-CN
defaultContentLanguage: zh
paginate: 10
theme: PaperMod

languages:
  zh:
    languageCode: zh-CN
    languageName: 简体中文
    weight: 1

enableInlineShortcodes: true #允许内联短码
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Choi's Notes
  description: "Eric Choi 的个人博客，记录生活，记录技术，记录折腾"
  keywords: [博客, Blog, Hugo, PaperMod, 技术, 开发, 程序员, .NET, .NET Core, C#, Java, JavaScript, TypeScript, Vue, Angular, JS, Node.js, 数码, 电脑, 手机, Apple, 苹果, macOS, iOS, iPhone, 安卓, Android, Windows, 微软, 视频号, 小红书]
  author: Eric
  images: ["/favicon.ico"]
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowLastMod: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon.ico"
    apple_touch_icon: "/favicon.ico"
    safari_pinned_tab: "/favicon.ico"

  label:
    text: "Choi's Notes"
    icon: /favicon.ico
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "你好\U0001F44B！这是我的写字台。"
    Content: 我会在这里记录工作，记录生活，以及一些好玩的。

  socialIcons:
    - name: twitter
      url: "https://twitter.com/404"
    - name: github
      url: "https://github.com/realchoi"
    - name: email
      url: "mailto:meetcds@foxmail.com"
    - name: RSS
      url: "index.xml"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
    #URL: "https://github.com/<path_to_repo>/content"
    #Text: "Suggest Changes" # edit text
    #appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: 📖分类
      url: /categories/
      weight: 10
    - identifier: tags
      name: 🏷️标签
      url: /tags/
      weight: 20
    - identifier: about
      name: 🐼关于我
      url: /about/
      weight: 30
    - identifier: friend
      name: 👫友链
      url: /friend/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true # 允许在 Markdown 中使用原生 HTML
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    # guessSyntax: true
    lineNos: true
    # style: monokai
